apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "padel-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  database: {{ .Values.postgresql.auth.database | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "padel-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
data:
  password: {{ .Values.redis.auth.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "padel-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
type: Opaque
data:
  secret: {{ .Values.jwt.secret | b64enc }}