apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: padel-platform-dev
  labels:
    app.kubernetes.io/name: padel-platform
    app.kubernetes.io/component: database
type: Opaque
data:
  # postgres username: padel_user (base64 encoded)
  username: cGFkZWxfdXNlcg==
  # postgres password: padel_password_dev (base64 encoded)
  password: cGFkZWxfcGFzc3dvcmRfZGV2
  # postgres database: padel_platform (base64 encoded)
  database: cGFkZWxfcGxhdGZvcm0=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: padel-platform-dev
  labels:
    app.kubernetes.io/name: padel-platform
    app.kubernetes.io/component: cache
type: Opaque
data:
  # redis password: redis_password_dev (base64 encoded)
  password: cmVkaXNfcGFzc3dvcmRfZGV2
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: padel-platform-dev
  labels:
    app.kubernetes.io/name: padel-platform
    app.kubernetes.io/component: auth
type: Opaque
data:
  # jwt secret: padel_jwt_secret_key_dev_2024 (base64 encoded)
  secret: cGFkZWxfand0X3NlY3JldF9rZXlfZGV2XzIwMjQ=